### ISSUE TITLE
Feature: User can sign up for an account

### ISSUE THREAD

**Issue by hqpham98** [hqpham98/pigeon-chat#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be welcomed with a home page with a sign in and sign up button. Pressing the sign up button will display a form for the user to input their information.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to allow POST requests to create a new user
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create home page with website name and a signin and signup b utton.
- [x] Create a React component SignupForm
- [x] Clicking Signup button should display the SignupForm
- [x] Submitting the Signup form should send the data to the server and create the appropriate record in the database.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
