### ISSUE TITLE
Feature: User can create conversation

### ISSUE THREAD

**Issue by hqpham98** [hqpham98/pigeon-chat#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Handle Socket event private-message-request and create conversation
- [x] Emit Socket event conversation-created to update conversation list and conversation view of client who initiated the request
- [x] Emit Socket event conversation-list-update to conversation participants

### ⚡ Client Tasks

- [x] Create a Direct Message Modal
  - [x] Live search results as friend name is being input into search box
  - [x] Emit Socket event to initiate conversation private-message-request
