### ISSUE TITLE
Feature: User can add friends

### ISSUE THREAD

**Issue by hqpham98** [hqpham98/pigeon-chat#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Implement express app.get to retrieve all friend requests received for a userID
- [x] Add Event Handler for friend-request-sent Socket event 
- [x] Send friend-request-received event to appropriate socket if request receiver  is online
- [x] Event Handler for friend-request-decision Socket event

### ⚡ Client Tasks

- [x] Display requests in Requests panel
- [x] Load Friend Requests on <Home/> mount
- [x] Send Request via Add Friend modal 
   - [x] Emit Socket event containing request information to Socket.IO server
- [x] Add Event Handler for friend-request-received event from Socket
- [x] Refresh both users' friend lists upon accepting friend request
- [x] Refresh receiving user's friend request list upon decision
